// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ansd/driving-time/maps (interfaces: Client)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	gomock "github.com/golang/mock/gomock"
	maps "googlemaps.github.io/maps"
	reflect "reflect"
)

// MockClient is a mock of Client interface
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
}

// MockClientMockRecorder is the mock recorder for MockClient
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// DistanceMatrix mocks base method
func (m *MockClient) DistanceMatrix(arg0 context.Context, arg1 *maps.DistanceMatrixRequest) (*maps.DistanceMatrixResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DistanceMatrix", arg0, arg1)
	ret0, _ := ret[0].(*maps.DistanceMatrixResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DistanceMatrix indicates an expected call of DistanceMatrix
func (mr *MockClientMockRecorder) DistanceMatrix(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DistanceMatrix", reflect.TypeOf((*MockClient)(nil).DistanceMatrix), arg0, arg1)
}
